services:
  app:
    image: ghcr.io/isnubi/ade-viewer:latest
    ports:
      - 5000:5000
    environment:
      - ADE_URL=https://ade.example.com
      - TZ=Europe/Paris
      - TIME_DELTA=0
    volumes:
      - /etc/localtime:/etc/localtime
    restart: unless-stopped
