services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8020:5000
    environment:
      - ADE_URL=https://planif.esiee.fr/jsp/custom/modules/plannings/anonymous_cal.jsp?resources=2129,3094,3095&projectId=12&calType=ical&nbWeeks=4
    volumes:
      - /etc/localtime:/etc/localtime
    restart: unless-stopped
